version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - "8123:8123"
    volumes:
      - $USERDIR/docker/homeassistant:/config
    network_mode: host
#    networks:
#      - traefik_proxy
#      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=home-assistant"
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    privileged: true

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
      - $USERDIR/docker/portainer:/data
      - $USERDIR/docker/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.whiteList.sourceRange=$HOME_IP/32"

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: always
    volumes:
      - $USERDIR/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - $USERDIR/docker/influxdb/db:/var/lib/influxdb
    environment:
      - INFLUX_GRAPHITE_ENABLED='true'
    ports:
      - "8086:8086"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    volumes:
      - $USERDIR/docker/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'secret'
    user: "1000"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:grafana.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.whiteList.sourceRange=$HOME_IP/32"

  esphomeyaml:
    container_name: esphomeyaml
    image: ottowinter/esphomeyaml:dev
    restart: unless-stopped
    ports:
      - "6052:6052"
      - "6123:6123"
    volumes:
      - $USERDIR/docker/esphomeyaml:/config
    command:
      - "/config"
      - "dashboard"
    privileged: true

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $USERDIR/docker/mosquitto/data:/mosquitto/data
      - $USERDIR/docker/mosquitto/config:/mosquitto/config
      - $USERDIR/docker/mosquitto/log:/mosquitto/log

  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    network_mode: host
#    networks:
#      - default
#      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/docker/traefik:/etc/traefik
      - $USERDIR/docker/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.whiteList.sourceRange=$HOME_IP/32"

  extractor:
    container_name: extractor
    image: felubra/traefik-certs-extractor
    restart: unless-stopped
    volumes:
      - $USERDIR/docker/traefik/acme/acme.json:/certs-extractor/acme.json:ro
      - $USERDIR/docker/certificates:/certs-extractor/certs/

  website:
    container_name: website
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - $USERDIR/docker/website:/usr/share/nginx/html:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=website"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:${DOMAINNAME},www.${DOMAINNAME}"
      - "traefik.frontend.redirect.regex=^https?://${DOMAINNAME}/(.*)"
      - "traefik.frontend.redirect.replacement=https://www.${DOMAINNAME}/$${1}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - $USERDIR/docker/mailserver/config:/tmp/docker-mailserver
    - $USERDIR/docker/certificates:/tmp/ssl:ro
    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/certs/${DOMAINNAME}.crt
    - SSL_KEY_PATH=/tmp/ssl/private/${DOMAINNAME}.key
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=0
    - ENABLE_POP3=0
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - SYS_PTRACE


  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    volumes:
      - $USERDIR/docker/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - $USERDIR/docker/nextcloud:/var/www/html
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:cloud.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  duplicati:
    image: duplicati/duplicati:canary
    container_name: duplicati
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - $USERDIR/docker/duplicati:/data
      - $USERDIR/docker:/source
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=duplicati"
      - "traefik.port=8200"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:backup.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.whiteList.sourceRange=$HOME_IP/32"

  bitwarden:
    image: mprasil/bitwarden:latest
    container_name: bitwarden
    restart: always
    ports: 
      - "8889:80"
    volumes:
      - $USERDIR/docker/bitwarden:/data
    environment:
      - SERVER_ADMIN_EMAL=bitwarden@${DOMAINNAME}
      - DOMAIN=bw.${DOMAINNAME}
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=smtp.${DOMAINNAME}
      - SMTP_FROM=bitwarden@${DOMAINNAME}
      - SMTP_PORT=465
      - SMTP_SSL=true
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bitwarden"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:bw.${DOMAINNAME}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
