version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: always
    depends_on:
      - influxdb
    volumes:
      - $USERDIR/docker/homeassistant:/config
    network_mode: host
    privileged: true

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
      - $USERDIR/docker/portainer:/data
      - $USERDIR/docker/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      - "traefik.frontend.redirect.replacement=$$1/portainer/"
      - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: always
    volumes:
      - $USERDIR/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - $USERDIR/docker/influxdb/db:/var/lib/influxdb
    environment:
      - INFLUX_GRAPHITE_ENABLED='true'
    ports:
      - "8086:8086"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    volumes:
      - $USERDIR/docker/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'secret'
    user: "1000"

  esphomeyaml:
    container_name: esphomeyaml
    image: ottowinter/esphomeyaml:dev
    restart: unless-stopped
    ports:
      - "6052:6052"
      - "6123:6123"
    volumes:
      - $USERDIR/docker/esphomeyaml:/config
    command:
      - "/config"
      - "dashboard"
    privileged: true

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $USERDIR/docker/mosquitto/data:/mosquitto/data
      - $USERDIR/docker/mosquitto/config:/mosquitto/config
      - $USERDIR/docker/mosquitto/log:/mosquitto/log

  radicale:
    container_name: radicale
    image: tomsquest/docker-radicale
    restart: always
    ports:
      - "5232:5232"
    read_only: true
    volumes:
      - $USERDIR/docker/radicale/data:/data
      - $USERDIR/docker/radicale/config:/config
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radicale"
      - "traefik.frontend.rule=Host:calendar.${DOMAINNAME}/"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=5232"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
#      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/docker/traefik:/etc/traefik
      - $USERDIR/docker/shared:/shared

  extractor:
    container_name: extractor
    image: felubra/traefik-certs-extractor
    restart: unless-stopped
    volumes:
      - $USERDIR/docker/traefik/acme/acme.json:/certs-extractor/acme.json:ro
      - $USERDIR/docker/certificates:/certs-extractor/certs/

  remcoharmsen.com:
    container_name: website
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - $USERDIR/docker/remcoharmsen.com:/usr/share/nginx/html:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=website"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.rule=Host:${DOMAINNAME},www.${DOMAINNAME}"
      - "traefik.frontend.redirect.regex=^https?://${DOMAINNAME}/(.*)"
      - "traefik.frontend.redirect.replacement=https://www.${DOMAINNAME}/$${1}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "110:110"
    - "995:995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - $USERDIR/docker/mailserver/config:/tmp/docker-mailserver
    - $USERDIR/docker/certificates:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POP3=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/certs/${DOMAINNAME}.crt
    - SSL_KEY_PATH=/tmp/ssl/private/${DOMAINNAME}.key
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
