homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks
   - type: homeassistant

config:

http:
  trusted_networks:
#    - 127.0.0.1
    - 192.168.0.0/24
    - 192.168.1.0/24
#    - 172.18.0.0/16
#    - 172.19.0.0/16

updater:
 
discovery:

history:

# logbook:

# map:

sun:
  
cloud:

automation: !include automations.yaml

climate: !include climate.yaml

conversation: !include conversations.yaml

device_tracker: !include device_tracker.yaml

frontend: !include frontend.yaml

#google_assistant: !include google_assistant.yaml

group: !include groups.yaml

light: !include lights.yaml

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

zone: !include zones.yaml


camera:
  - platform: ffmpeg
    name: Camera
    input: !secret camera_url

influxdb:
  host: 192.168.1.14

mqtt:
#  broker: m21.cloudmqtt.com
#  port: 17322
#  username: homeassistant
#  password: !secret cloudmqtt_password
#  discovery: true
  broker: 192.168.1.14
  port: 1883
  discovery: true

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey

media_player LibreELEC:
  - platform: kodi
    host: 192.168.1.54
    port: 8080
    username: !secret kodi_username
    password: !secret kodi_password

xiaomi_aqara:
  discovery_retry: 20
  gateways:
    - host: 192.168.1.42
      mac: !secret aqara_mac
      key: !secret aqara_key





input_datetime:
  woonkamerverlichting_ochtend_aan:
    name: "Verlichting ochtend aan"
    has_date: false
    has_time: true
    initial: '05:30'
  woonkamerverlichting_avond_uit:
    name: "Verlichting avond uit"
    has_date: false
    has_time: true
    initial: '23:00'
  woonkamerverlichting_weekend_avond_uit:
    name: "Verlichting weekendavond uit"
    has_date: false
    has_time: true
    initial: '0:00'
  woonkamerverlichting_offset_ochtend:
    name: "Offset verlichting uit"
    has_date: false
    has_time: true
    initial: '0:30'
  woonkamerverlichting_offset_middag:
    name: "Offset verlichting aan"
    has_date: false
    has_time: true
    initial: '0:45'

