logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[web]
address = ":8080"
  [web.auth.basic]
  usersFile = "/shared/.htpasswd"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"

    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

#    [entryPoints.https.whitelist]
#      sourceRange = ["85.144.103.129"]
#      useXForwardedFor = true

[file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Let's encrypt configuration
[acme]
email = "remcoharmsen@hotmail.com" #any email id will work
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
acmeLogging = true 
onDemand = false #create certificate when container is created
#onHostRule = true

# httpChallenge voor subdomeinen
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
   main = "remcoharmsen.com"
   sans = ["www.remcoharmsen.com","mail.remcoharmsen.com","smtp.remcoharmsen.com","imap.remcoharmsen.com","home.remcoharmsen.com","cloud.remcoharmsen.com","bw.remcoharmsen.com","grafana.remcoharmsen.com","portainer.remcoharmsen.com","backup.remcoharmsen.com"]

# dnsChallenge voor wildcards
#entryPoint = "https"
#  [acme.dnsChallenge]
#  provider = "transip"
#  delayBeforeCheck = 0

#[[acme.domains]]
#  main = "*.remcoharmsen.com"

# Connection to docker host system (docker.sock)
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "remcoharmsen.com"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false
