esphomeyaml:
  name: esp32_node2
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'RioMare'
  password: 'RioMareLikeVolharding'
  manual_ip:
    static_ip: 192.168.1.47
    gateway: 192.168.1.1
    subnet: 255.255.255.0

mqtt:
  broker: 192.168.1.14
  port: 1883
  username: 'ESP32'
  password: 'ZVgnuxVMLEn0'

logger: {}

ota:
  safe_mode: true

sensor:
- platform: pulse_counter
  pin: 'GPIO15'
  name: 'Pulse Counter'

